#ifndef __MyProject2MainFrameBase__
#define __MyProject2MainFrameBase__

/**
@file
Subclass of MainFrameBase, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing MainFrameBase */
class MyProject2MainFrameBase : public MainFrameBase
{
	protected:
		// Handlers for MainFrameBase events.
		void FrameOnPaint( wxPaintEvent& event );
		void FrameOnSize( wxSizeEvent& event );
		void FrameOnUpdateUI( wxUpdateUIEvent& event );
		void BtnImportImageClick( wxCommandEvent& event );
		void OnScrollRed( wxScrollEvent& event );
		void OnScrollGreen( wxScrollEvent& event );
		void OnScrollBlue( wxScrollEvent& event );
		void BtnBichromyClick( wxCommandEvent& event );
		void btnRestoreImageClick( wxCommandEvent& event );
		void bichromyGradientChanged( wxColourPickerEvent& event );
		void BtnLoadParametersClick( wxCommandEvent& event );
		void BtnSaveParametersClick( wxCommandEvent& event );
		void OnScrollMixer( wxScrollEvent& event );
		void ToggleKeepingHueClick( wxCommandEvent& event );
		void ColorChanged( wxColourPickerEvent& event );
		void BtnSaveImageClick( wxCommandEvent& event );
	public:
		/** Constructor */
		MyProject2MainFrameBase( wxWindow* parent );
	//// end generated class members






};

#endif // __MyProject2MainFrameBase__
